### ISSUE TITLE
劇場モデルにおけるストーリーの作成

### ISSUE THREAD

**Issue by poster-keisuke** [poster-keisuke/sample#14]
## WHAT
明日の発表の際に利用するモデルのストーリーを各自２種類持ってくる。
その際に文化祭のような複雑なものではなく、バイク好きなオフ会のような、「広告主」、「主催者」、「参加者」の3者が参加するイベントを考える。

谷合　フリマ、ストリートライブ
志賀　ゲーム大会、オフ会
中村　検討中

**Comment by Shiga-Takuya** [comment]
[Office Lens 20160512-170212.pdf](https://github.com/poster-keisuke/sample/files/260821/Office.Lens.20160512-170212.pdf)

劇場型のステークホルダーの組み合わせを考えた結果、図のような8つになった。
この組み合わせごとのシナリオを考えてくる。
CJMではなく、各ステークホルダーの関係を図（前のMTGで作った全体の流れを表すやつ）でやった方が良い
