### ISSUE TITLE
SXD webサイト作成

### ISSUE THREAD

**Issue by Shiga-Takuya** [poster-keisuke/sample#9]
## WHAT
2016年用のSXDwebサイトの作成

## WHY
3年生勧誘のため

## HOW
HTML、CSS、思い出動画など

**Comment by poster-keisuke** [comment]
4/25日まで　
・三年生向けwebサイトのプロトタイピング及び、参考となるデザインの収集

■参考Webページ
■プロトタイピング(最低トップページ)

**Comment by poster-keisuke** [comment]
参考
http://sxd2015.strikingly.com/
